### ISSUE TITLE
Version 1.2?

### ISSUE THREAD

**Issue by ghost** [poseidn/KungFoo#1]
Hi,

currently the playstore shows 1.2 as the current version of the app:

https://play.google.com/store/apps/details?id=com.onetwofivegames.kungfoobarracuda

where https://github.com/poseidn/KungFoo/releases has 1.0 and https://github.com/poseidn/KungFoo/commit/33136cc4bbfdcb624634acdcd182e6be1a587d23 has 1.1.

Are there any reasons for this differences?

**Comment by poseidn** [comment]
Hi,
thanks for pointing that out. I now pushed also the 1.2 tag and the 1.2 Android manifest file to github, which was before only in my local repository.
